
import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jdatepicker.DateModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import spr.beans.DoctorProfileTable;
import spr.beans.NurseProfileTable;
import spr.hib.dao.LogicalCodeDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class AdminDashboard extends javax.swing.JFrame {

    private DoctorProfileTable DoctorProfileTable;

    /**
     * Creates new form PatientDashboard2
     */
    public AdminDashboard() {
        initComponents();
        Date date = new Date();
        DateFormat df = DateFormat.getDateInstance(DateFormat.FULL);
        jLabel8.setText(df.format(date));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPasswordField3 = new javax.swing.JPasswordField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jDatePicker3 = new org.jdatepicker.JDatePicker();
        jButton3 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jDatePicker1 = new org.jdatepicker.JDatePicker();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPasswordField2 = new javax.swing.JPasswordField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jDatePicker2 = new org.jdatepicker.JDatePicker();
        jButton2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setFocusTraversalPolicyProvider(true);
        jPanel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("VIEW PROFILE", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("UPDATE PROFILE\n", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane2.addTab("DELETE PROFILE\n", jPanel7);

        jPanel3.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        jTabbedPane1.addTab("PATIENT PROFILE\n\n", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane3.addTab("VIEW PROFILE", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel24.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel24FocusGained(evt);
            }
        });
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel33.setText("DOCTOR PROFILE UPDATION FORM");
        jPanel24.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setText("ID:");
        jPanel24.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setText("FULL NAME:");
        jPanel24.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setText("EMAIL ID:");
        jPanel24.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setText("ADDRESS:");
        jPanel24.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setText("QUALIFICATION:");
        jPanel24.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setText("EXPERIENCE:");
        jPanel24.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setText("PASSWORD:");
        jPanel24.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 170, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setText("POST:");
        jPanel24.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 170, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setText("GENDER:");
        jPanel24.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 170, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel43.setText("DOB:");
        jPanel24.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 170, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setText("CONTACT NO:");
        jPanel24.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 170, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel45.setText("ACHIEVEMENTS:");
        jPanel24.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 170, -1));

        jTextField14.setText("ENTER DOCTOR ID HERE");
        jTextField14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField14FocusGained(evt);
            }
        });
        jTextField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField14MouseClicked(evt);
            }
        });
        jPanel24.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 430, 30));

        jTextField15.setText("ENTER FULL NAME HERE");
        jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField15MouseClicked(evt);
            }
        });
        jPanel24.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 430, 30));

        jTextField16.setText("ENTER EMAIL ID HERE");
        jTextField16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField16MouseClicked(evt);
            }
        });
        jPanel24.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 430, 30));

        jTextField17.setText("ENTER DOCTOR QUALIFICATION (DEGREES)HERE.");
        jTextField17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField17MouseClicked(evt);
            }
        });
        jPanel24.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 430, 30));

        jTextField18.setText("ENTER DOCTOR WORK EXPERIENCE HERE");
        jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField18MouseClicked(evt);
            }
        });
        jPanel24.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 430, 30));

        jTextField19.setText("ENTER CONTACT NO HERE");
        jTextField19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField19MouseClicked(evt);
            }
        });
        jPanel24.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, 360, 30));

        jTextField20.setText("ENTER ACHIEVEMENTS HERE");
        jTextField20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField20MouseClicked(evt);
            }
        });
        jPanel24.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 360, 30));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("ENTER ADDRESS HERE");
        jTextArea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea3);

        jPanel24.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 430, -1));

        jPasswordField3.setText("ENTER PASSWORD HERE");
        jPasswordField3.setEchoChar('\u0000');
        jPasswordField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField3MouseClicked(evt);
            }
        });
        jPanel24.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 360, 30));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT POST", "CARDIOLOGIST", "ENT SPECIALIST", "PHYSICIAN", "PEDIATRICIAN ", "GYNACOLOGIST", " " }));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
        });
        jPanel24.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 360, 30));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton5.setText("MALE");
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseClicked(evt);
            }
        });
        jPanel24.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton6.setText("FEMALE");
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton6MouseClicked(evt);
            }
        });
        jPanel24.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 160, -1, -1));

        jDatePicker3.setToolTipText("10 july 2005");
        jDatePicker3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDatePicker3MouseClicked(evt);
            }
        });
        jPanel24.add(jDatePicker3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, 360, 20));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 120, -1));

        jPanel9.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 550));

        jTabbedPane3.addTab("UPDATE PROFILE", jPanel9);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel46.setText("DOCTOR PROFILE DELETION FORM");
        jPanel25.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel47.setText("ID:");
        jPanel25.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 40, -1));

        jTextField21.setText("ENTER ID HERE");
        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField21MouseClicked(evt);
            }
        });
        jPanel25.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 400, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setText("PASSWORD:");
        jPanel25.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, -1));

        jPasswordField4.setText("ENTER PASSWORD HERE");
        jPasswordField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField4.setEchoChar('\u0000');
        jPasswordField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField4MouseClicked(evt);
            }
        });
        jPanel25.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 400, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 100, -1));

        jPanel12.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 470));

        jTabbedPane3.addTab("DELETE PROFILE", jPanel12);

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("DOCTOR PROFILE CREATION FORM");
        jPanel21.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("ID:");
        jPanel21.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("FULL NAME:");
        jPanel21.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("EMAIL ID:");
        jPanel21.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("ADDRESS:");
        jPanel21.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("QUALIFICATION:");
        jPanel21.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("EXPERIENCE:");
        jPanel21.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("PASSWORD:");
        jPanel21.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 170, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("POST:");
        jPanel21.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 170, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("GENDER:");
        jPanel21.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 170, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("DOB:");
        jPanel21.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 170, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("CONTACT NO:");
        jPanel21.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 170, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("ACHIEVEMENTS:");
        jPanel21.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 170, -1));

        jTextField1.setText("ENTER DOCTOR ID HERE");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel21.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 430, 30));

        jTextField2.setText("ENTER FULL NAME HERE");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel21.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 430, 30));

        jTextField3.setText("ENTER EMAIL ID HERE");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jPanel21.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 430, 30));

        jTextField4.setText("ENTER DOCTOR QUALIFICATION (DEGREES)HERE.");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jPanel21.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 430, 30));

        jTextField5.setText("ENTER DOCTOR WORK EXPERIENCE HERE");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jPanel21.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 430, 30));

        jTextField6.setText("ENTER CONTACT NO HERE");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jPanel21.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, 360, 30));

        jTextField13.setText("ENTER ACHIEVEMENTS HERE");
        jTextField13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField13MouseClicked(evt);
            }
        });
        jPanel21.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 270, 360, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("ENTER ADDRESS HERE");
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel21.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 430, -1));

        jPasswordField1.setText("ENTER PASSWORD HERE");
        jPasswordField1.setEchoChar('\u0000');
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel21.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 360, 30));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT POST", "CARDIOLOGIST", "ENT SPECIALIST", "PHYSICIAN", "PEDIATRICIAN ", "GYNACOLOGIST", " " }));
        jPanel21.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 360, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton1.setText("MALE");
        jPanel21.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton2.setText("FEMALE");
        jPanel21.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 160, -1, -1));

        jDatePicker1.setToolTipText("10 july 2005");
        jPanel21.add(jDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, 360, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("CREATE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 120, -1));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 550));

        jTabbedPane3.addTab("CREATE PROFILE", jPanel20);

        jPanel4.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        jTabbedPane1.addTab("DOCTOR PROFILE", jPanel4);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane4.addTab("VIEW PROFILE", jPanel14);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane4.addTab("UPDATE PROFILE ", jPanel15);

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane4.addTab("DELETE PROFILE", jPanel16);

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("NURSE PROFILE CREATION FORM");
        jPanel23.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("ID:");
        jPanel23.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("FULL NAME:");
        jPanel23.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("EMAIL ID:");
        jPanel23.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("ADDRESS:");
        jPanel23.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("QUALIFICATION:");
        jPanel23.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("EXPERIENCE:");
        jPanel23.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("PASSWORD:");
        jPanel23.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 170, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("GENDER:");
        jPanel23.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 170, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("DOB:");
        jPanel23.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 170, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("CONTACT NO:");
        jPanel23.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 170, -1));

        jTextField7.setText("ENTER NURSE ID HERE");
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jPanel23.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 430, 30));

        jTextField8.setText("ENTER FULL NAME HERE");
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jPanel23.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 430, 30));

        jTextField9.setText("ENTER EMAIL ID HERE");
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jPanel23.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 430, 30));

        jTextField10.setText("ENTER NURSE QUALIFICATION (DEGREES)HERE.");
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jPanel23.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 430, 30));

        jTextField11.setText("ENTER NURSE WORK EXPERIENCE HERE");
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        jPanel23.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 430, 30));

        jTextField12.setText("ENTER CONTACT NO HERE");
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });
        jPanel23.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, 360, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("ENTER ADDRESS HERE");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel23.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 430, -1));

        jPasswordField2.setText("ENTER PASSWORD HERE");
        jPasswordField2.setEchoChar('\u0000');
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPanel23.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 360, 30));

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton3.setText("MALE");
        jPanel23.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRadioButton4.setText("FEMALE");
        jPanel23.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 110, -1, -1));
        jPanel23.add(jDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, 360, 20));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("CREATE");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 120, -1));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 550));

        jTabbedPane4.addTab("CREATE PROFILE", jPanel22);

        jPanel13.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        jTabbedPane1.addTab("NURSE PROFILE", jPanel13);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("FEEDBACKS", jPanel17);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane5.addTab("FOOD ORDERS", jPanel18);

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane5.addTab("MEDICINE ORDERS", jPanel19);

        jPanel2.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 650));

        jTabbedPane1.addTab("ORDERS", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1280, 590));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Logout Icon.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 70, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Information button.png"))); // NOI18N
        jPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Help Icon.png"))); // NOI18N
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 70, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Settings Icon.png"))); // NOI18N
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 90));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Quick Links----" }));
        jPanel11.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 240, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 250, 30));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 590));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("COPYRIGHT @ 2025 CAREELEVATE PVT LTD ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("COPYRIGHT @ 2025 CAREELEVATE PVT LTD\n");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(895, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3)
                    .addContainerGap(889, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(44, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(17, 17, 17)))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1280, 90));

        jMenuBar1.setBorder(null);

        jMenu1.setBorder(null);
        jMenu1.setText("PROFILE");
        jMenu1.setIconTextGap(9);
        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("      SETTINGS     ");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("HELP");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("TOOLS");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("WINDOWS");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("VIEW");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("THEME");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("SHOW  TABS");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int result = JOptionPane.showConfirmDialog(this,"Do you really want to exit?","Closing message",JOptionPane.YES_NO_OPTION);
        if(result == 0){
            this.dispose();
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ApplicationContext context = new ClassPathXmlApplicationContext("/SpringXmlConfig.xml");
        LogicalCodeDAO dao=(LogicalCodeDAO)context.getBean("firstStep");
        String id=jTextField1.getText();
        String fullName=jTextField2.getText();
        String emailId=jTextField3.getText();
        String address=jTextArea1.getText();
        String qualification=jTextField4.getText();
        String experience=jTextField5.getText();
        String password=new String(jPasswordField1.getPassword());
        String post=(String)jComboBox1.getSelectedItem();
        String achievements=jTextField13.getText();
        String gender = null;
        if(jRadioButton1.isSelected()){
             gender=jRadioButton1.getText();
        }
        else if(jRadioButton2.isSelected()){
             gender=jRadioButton2.getText();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the gender");
        }
        DateModel DOB=jDatePicker1.getModel();
        String dob=DOB.getDay()+""+DOB.getMonth()+""+DOB.getYear();
        String contactNo=jTextField6.getText();
        DoctorProfileTable doctorprofiletable=new DoctorProfileTable(id,password,fullName,emailId,address,qualification,experience,achievements,post,gender,dob,contactNo);
        dao.insertDoctorProfile(doctorprofiletable);
        JOptionPane.showMessageDialog(this,"Record Successfully inserted");
        new AdminDashboard().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ApplicationContext context = new ClassPathXmlApplicationContext("/SpringXmlConfig.xml");
        LogicalCodeDAO dao=(LogicalCodeDAO)context.getBean("firstStep");
        String id=jTextField7.getText();
        String fullName=jTextField8.getText();
        String emailId=jTextField9.getText();
        String address=jTextArea2.getText();
        String qualification=jTextField10.getText();
        String experience=jTextField11.getText();
        String password=new String(jPasswordField2.getPassword());
        String gender = null;
        if(jRadioButton3.isSelected()){
             gender=jRadioButton3.getText();
        }
        else if(jRadioButton4.isSelected()){
             gender=jRadioButton4.getText();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the gender");
        }
        DateModel DOB=jDatePicker1.getModel();
        String dob=DOB.getDay()+""+DOB.getMonth()+""+DOB.getYear();
        String contactNo=jTextField12.getText();
        NurseProfileTable nurseprofiletable=new NurseProfileTable(id,password,fullName,emailId,address,qualification,experience,gender,dob,contactNo);
        dao.insertNurseProfile(nurseprofiletable);
        JOptionPane.showMessageDialog(this,"Record Successfully inserted");
        new AdminDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
        jTextField1.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
        jTextField2.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        jTextField3.setText("");
        jTextField3.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        jTextArea1.setText("");
        jTextArea1.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
        jTextField4.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setText("");
        jTextField5.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        jTextField6.setText("");
        jTextField6.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
        jPasswordField1.setEchoChar('*');
        jPasswordField1.setForeground(Color.black);
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        jTextField7.setText("");
        jTextField7.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        jTextField8.setText("");
        jTextField8.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        jTextField10.setText("");
        jTextField10.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        jTextField9.setText("");
        jTextField9.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        jTextField11.setText("");
        jTextField11.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        jTextField12.setText("");
        jTextField12.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField12MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        jPasswordField2.setText("");
        jPasswordField2.setEchoChar('*');
        jPasswordField2.setForeground(Color.black);
        
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jTextField13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField13MouseClicked
        jTextField13.setText("");
        jTextField13.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextField13MouseClicked

    private void jTextField14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField14MouseClicked
        
    }//GEN-LAST:event_jTextField14MouseClicked

    private void jTextField15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField15MouseClicked
        
    }//GEN-LAST:event_jTextField15MouseClicked

    private void jTextField16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField16MouseClicked
        
    }//GEN-LAST:event_jTextField16MouseClicked

    private void jTextField17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField17MouseClicked
        
    }//GEN-LAST:event_jTextField17MouseClicked

    private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField18MouseClicked
        
    }//GEN-LAST:event_jTextField18MouseClicked

    private void jTextField19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField19MouseClicked
        
    }//GEN-LAST:event_jTextField19MouseClicked

    private void jTextField20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField20MouseClicked
        
    }//GEN-LAST:event_jTextField20MouseClicked

    private void jTextArea3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea3MouseClicked
        
    }//GEN-LAST:event_jTextArea3MouseClicked

    private void jPasswordField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField3MouseClicked
        
    }//GEN-LAST:event_jPasswordField3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseClicked

    }//GEN-LAST:event_jRadioButton5MouseClicked

    private void jRadioButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MouseClicked
        
    }//GEN-LAST:event_jRadioButton6MouseClicked

    private void jDatePicker3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDatePicker3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDatePicker3MouseClicked

    private void jPanel24FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel24FocusGained
       
    }//GEN-LAST:event_jPanel24FocusGained

    private void jTextField14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField14FocusGained
        
    }//GEN-LAST:event_jTextField14FocusGained

    private void jTextField21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField21MouseClicked
        jTextField21.setText("");
        jTextField21.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextField21MouseClicked

    private void jPasswordField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField4MouseClicked
        jPasswordField4.setText("");
        jPasswordField4.setEchoChar('*');
        jPasswordField4.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jPasswordField4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ApplicationContext context = new ClassPathXmlApplicationContext("/SpringXmlConfig.xml");
        LogicalCodeDAO dao =(LogicalCodeDAO)context.getBean("firstStep");
        String id = jTextField21.getText();
        String password=new String(jPasswordField4.getPassword());
        boolean result = dao.checkDoctorLogin(id, password);
        if(result){
            dao.deleteDoctorProfile(id,password);
            JOptionPane.showMessageDialog(this,"Record deleted successfully");
        }
        else{
            JOptionPane.showMessageDialog(this,"No record exists for the provided id/password.\n Please check your credentials again.");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private org.jdatepicker.JDatePicker jDatePicker1;
    private org.jdatepicker.JDatePicker jDatePicker2;
    private org.jdatepicker.JDatePicker jDatePicker3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
