
import java.io.File;
import javax.media.Manager;
import javax.media.Player;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Flash extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Flash
     */
    public Flash() {
        initComponents();
        Thread thread = new Thread(this);//ref of current class
        thread.start();
    }

    @Override
    public void run() {
        try{
            File file = new File("D:\\NetBeansProjects\\CareElevate\\src\\media\\Calm Music1.mpg");
            Player player = Manager.createRealizedPlayer(file.toURI().toURL());
            player.start();
            String ch[]={"loading Flash....","loading database tables....","loading login window...."};
            jLabel7.setText(ch[0]);
            Thread.sleep(1000);
            for(int i=jProgressBar1.getMinimum();i<=jProgressBar1.getMaximum();i++){
                Thread.sleep(210); 
                jProgressBar1.setValue(i);
                jLabel7.setText(ch[1]);
                jLabel6.setText(i+"%");
                }
            player.stop();
            jLabel7.setText(ch[2]);
            Thread.sleep(2000);
            
            new Login().setVisible(true);
            this.dispose();//to close the flash window
//            System.exit(0);
            ApplicationContext context = new ClassPathXmlApplicationContext("/SpringXmlConfig.xml");
            context.getBean("firstStep");
            }catch(Exception ex){};
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 354, 650, 10));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("CareElevate");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Elevating Lives through digital \ncare.\n");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 410, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Doctor_logo_rod_rotating_gif_concept-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 200, 210));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Red_cross_2.-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 160, 100));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/BackgroundWallpaper 2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Flash().setVisible(true);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
